### ISSUE TITLE
Repository name standardization for Docker deployments

### ISSUE THREAD

**Issue by jkarppinen** [jansipil/Doorbell#19]
When utilizing the `image` parameter of `docker-compose.yml` for achieving local builds with predefined image build name, the following error occurs:

### Command
```
docker compose up -d
```

### Error
```
unable to get image 'jansipil/Doorbell': Error response from daemon: invalid reference format: repository name (jansipil/Doorbell) must be lowercase
```

### docker-compose.yml
```
services:
  doorbell:
    container_name: doorbell_app
    build: .
    image: jansipil/Doorbell
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - DOORBELL_PORT=8080
    volumes:
      - .:/app
      - /app/node_modules  # Prevents overwriting node_modules inside the container
    command: ["node", "webserver.js"]
    restart: unless-stopped
```

### Fix proposal
Renaming repository from `Doorbell` to `doorbell` would create integrity between the repository name and created Docker images. Perhaps this might be a blocker for Docker Hub push, if that comes to consideration one day.
